Fixe bugs main structure
NikitaBondarevv/maguwoHost pull request #2
Opened 2022-08-14 11:53 UTC by NikitaBondarevv

2022-08-14 16:52 UTC, iliatcymbal requested changes

2022-08-14 16:52 UTC, iliatcymbal commented on styles.css
>    width: 100px;
don't need width here

2022-08-14 16:52 UTC, iliatcymbal commented on styles.css
> +  margin: 42px 0 0 12px;
- no need left margin
- top margin should be set as a padding on the parent element (`.nav-block`)

2022-08-14 16:52 UTC, iliatcymbal commented on styles.css
>  }
link shouldn't be clickable outside the text
![1](https://user-images.githubusercontent.com/6584990/184546911-9012d8e5-b3c9-4380-bde7-ff795bbb335f.png)

2022-08-15 07:10 UTC, iliatsymbal approved these changes

2022-08-15 10:23 UTC, merged